[analytic.metadata]
categories = ["detect"]
confidence = "high"
contributors = ["David French"]
created_date = "8/16/2019"
description = "Identifies an unexpected process loading the Windows Credential Vault DLL in preparation of enumerating/stealing a user's saved credentials."
id = "679560ee-0ea0-4358-bf83-e4c478d9d1c8"
name = "Suspicious Process Loading Credential Vault DLL"
os = ["windows"]
tactics = ["Credential Access"]
techniques = ["T1003"]
updated_date = "8/16/2019"
references = ["https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-8de93338c16"]

[analytic]
query = '''
image_load where process_name != "vaultcmd.exe" and
  image_name == "vaultcli.dll"
'''
