[analytic.metadata]
categories = ["detect"]
confidence = "high"
contributors = ["David French"]
created_date = "8/16/2019"
description = "Identifies use of the Credential Vault command line interface to enumerate a user's saved credentials."
id = "11968244-6db0-4e03-886c-e3983f9d9024"
name = "Credential Enumeration via Credential Vault CLI"
os = ["windows"]
tactics = ["Credential Access"]
techniques = ["T1003"]
updated_date = "8/16/2019"
references = ["https://rastamouse.me/2017/08/jumping-network-segregation-with-rdp/", "https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-8de93338c16"]

[analytic]
query = '''
process where subtype.create and
  process_name == "vaultcmd.exe" and
  command_line == "* /list*"
'''
