[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["David French"]
created_date = "8/16/2019"
description = "Identifies the execution of Windows Management Instrumentation (WMI) via a Microsoft Office application."
id = "e6be5ffe-c765-4e13-962d-7eaae07aeaec"
name = "WMI Execution via Microsoft Office Application"
os = ["windows"]
tactics = ["Execution"]
techniques = ["T1047"]
updated_date = "8/16/2019"
references = ["https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-8de93338c16"]

[analytic]
query = '''
image_load where
  process_name in ("excel.exe", "winword.exe",
                   "powerpnt.exe", "outlook.exe") and
  image_name in ("wbemdisp.dll", "wbemcomn.dll", "wbemprox.dll",
                 "wmiutils.dll", "wbemsvc.dll", "fastprox.dll")
'''
